export interface Movie {
  id: number;
  title: string;
  description: string;
  image: string;
  year: number;
  rating: string;
  duration: string;
  genre: string[];
  isFeatured?: boolean;
}

export const movies: Movie[] = [
  {
    id: 1,
    title: "Shadow Strike",
    description: "Un agent secret doit arrêter une organisation criminelle mondiale avant qu'il ne soit trop tard. Action explosive et rebondissements garantis.",
    image: "https://images.unsplash.com/photo-1765510296004-614b6cc204da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhY3Rpb24lMjBtb3ZpZSUyMHBvc3RlcnxlbnwxfHx8fDE3NzMxOTUyNDJ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2024,
    rating: "16+",
    duration: "2h 15min",
    genre: ["Action", "Thriller"],
    isFeatured: true,
  },
  {
    id: 2,
    title: "Odyssée Galactique",
    description: "Dans un futur lointain, l'humanité explore les confins de l'univers à la recherche d'une nouvelle planète habitable.",
    image: "https://images.unsplash.com/photo-1644772310791-deb96e24ee65?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzY2ktZmklMjBmdXR1cmlzdGljfGVufDF8fHx8MTc3MzIwNTYzM3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2025,
    rating: "13+",
    duration: "2h 45min",
    genre: ["Science-Fiction", "Aventure"],
  },
  {
    id: 3,
    title: "Sous le Ciel Étoilé",
    description: "Une histoire d'amour intemporelle qui traverse les époques et défie tous les obstacles.",
    image: "https://images.unsplash.com/photo-1658851866325-49fb8b7fbcb2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyb21hbnRpYyUyMGNvdXBsZSUyMHN1bnNldHxlbnwxfHx8fDE3NzMyNzc3Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2024,
    rating: "10+",
    duration: "1h 55min",
    genre: ["Romance", "Drame"],
  },
  {
    id: 4,
    title: "La Grande Farce",
    description: "Une comédie hilarante sur un groupe d'amis qui se retrouvent dans des situations absurdes.",
    image: "https://images.unsplash.com/photo-1762417421419-f5f8ecfe9136?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21lZHklMjB0aGVhdGVyJTIwbWFza3N8ZW58MXx8fHwxNzczMjczNDU3fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2023,
    rating: "13+",
    duration: "1h 40min",
    genre: ["Comédie"],
  },
  {
    id: 5,
    title: "L'Ombre de la Forêt",
    description: "Un thriller horrifique qui se déroule dans une forêt maudite où personne ne sort vivant.",
    image: "https://images.unsplash.com/photo-1639986587553-1d994ffc66d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob3Jyb3IlMjBkYXJrJTIwZm9yZXN0fGVufDF8fHx8MTc3MzI3Nzc3OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2024,
    rating: "18+",
    duration: "1h 50min",
    genre: ["Horreur", "Thriller"],
  },
  {
    id: 6,
    title: "Planète Sauvage",
    description: "Un documentaire fascinant sur la vie sauvage et les écosystèmes menacés de notre planète.",
    image: "https://images.unsplash.com/photo-1719743441581-632023e3d2ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb2N1bWVudGFyeSUyMG5hdHVyZSUyMHdpbGRsaWZlfGVufDF8fHx8MTc3MzI1NjgxMXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2025,
    rating: "Tous publics",
    duration: "1h 30min",
    genre: ["Documentaire", "Nature"],
  },
  {
    id: 7,
    title: "Nuits Urbaines",
    description: "Un drame intense qui explore les vies interconnectées dans une métropole moderne.",
    image: "https://images.unsplash.com/photo-1579480538030-1763eae4903e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkcmFtYSUyMGNpdHlzY2FwZSUyMG5pZ2h0fGVufDF8fHx8MTc3MzI3Nzc4MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2024,
    rating: "16+",
    duration: "2h 10min",
    genre: ["Drame"],
  },
  {
    id: 8,
    title: "Code Rouge",
    description: "Un thriller haletant où chaque seconde compte dans une course contre la montre.",
    image: "https://images.unsplash.com/photo-1578318043589-97a29602f7d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aHJpbGxlciUyMHN1c3BlbnNlJTIwY2l0eXxlbnwxfHx8fDE3NzMyNzc3ODB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2023,
    rating: "16+",
    duration: "1h 58min",
    genre: ["Thriller", "Action"],
  },
  {
    id: 9,
    title: "Le Royaume Enchanté",
    description: "Une aventure fantastique dans un monde magique peuplé de créatures extraordinaires.",
    image: "https://images.unsplash.com/photo-1766156555244-572b9757433b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYW50YXN5JTIwY2FzdGxlJTIwbWFnaWNhbHxlbnwxfHx8fDE3NzMyNzc3ODF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2025,
    rating: "Tous publics",
    duration: "2h 20min",
    genre: ["Fantastique", "Aventure"],
  },
  {
    id: 10,
    title: "Couleurs Animées",
    description: "Un film d'animation vibrant qui célèbre l'imagination et la créativité.",
    image: "https://images.unsplash.com/photo-1767925539079-57e614ea83f3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbmltYXRlZCUyMGNvbG9yZnVsJTIwY2hhcmFjdGVyc3xlbnwxfHx8fDE3NzMyNzc3ODF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2024,
    rating: "Tous publics",
    duration: "1h 35min",
    genre: ["Animation", "Famille"],
  },
  {
    id: 11,
    title: "Au Sommet du Monde",
    description: "L'histoire vraie d'une expédition d'alpinistes qui tentent de conquérir l'impossible.",
    image: "https://images.unsplash.com/photo-1708553479135-c3272e5aea2a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZHZlbnR1cmUlMjBtb3VudGFpbiUyMGNsaW1iaW5nfGVufDF8fHx8MTc3MzI0Njg2OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2023,
    rating: "13+",
    duration: "2h 05min",
    genre: ["Aventure", "Drame"],
  },
  {
    id: 12,
    title: "L'Énigme Nocturne",
    description: "Un détective enquête sur une série de crimes mystérieux dans une ville sombre.",
    image: "https://images.unsplash.com/photo-1771774469852-0c640838429f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxteXN0ZXJ5JTIwZGV0ZWN0aXZlJTIwbm9pcnxlbnwxfHx8fDE3NzMxODI2NDV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2024,
    rating: "16+",
    duration: "2h 00min",
    genre: ["Mystère", "Thriller"],
  },
  {
    id: 13,
    title: "Les Gardiens",
    description: "Des super-héros s'unissent pour protéger la ville d'une menace extraterrestre.",
    image: "https://images.unsplash.com/photo-1759736810854-7ef297dec79d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXBlcmhlcm8lMjBjaXR5c2NhcGV8ZW58MXx8fHwxNzczMjc3NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2025,
    rating: "13+",
    duration: "2h 30min",
    genre: ["Action", "Science-Fiction"],
  },
  {
    id: 14,
    title: "Poussière d'Ouest",
    description: "Un western moderne qui raconte l'histoire d'un hors-la-loi en quête de rédemption.",
    image: "https://images.unsplash.com/photo-1610671134286-0580738274a1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZXN0ZXJuJTIwZGVzZXJ0JTIwbGFuZHNjYXBlfGVufDF8fHx8MTc3MzI1NDMzOHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2024,
    rating: "16+",
    duration: "2h 12min",
    genre: ["Western", "Drame"],
  },
  {
    id: 15,
    title: "Voyage Interstellaire",
    description: "Une exploration épique à travers l'espace pour découvrir les secrets de l'univers.",
    image: "https://images.unsplash.com/photo-1500185497267-d635f9c5e90f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGFjZSUyMGdhbGF4eSUyMHN0YXJzfGVufDF8fHx8MTc3MzI3MTk1MXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2025,
    rating: "10+",
    duration: "2h 40min",
    genre: ["Science-Fiction", "Aventure"],
  },
  {
    id: 16,
    title: "La Traque",
    description: "Un enquêteur tente de résoudre une affaire criminelle complexe avant qu'il ne soit trop tard.",
    image: "https://images.unsplash.com/photo-1721269282172-f59b96bc9060?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmltZSUyMGludmVzdGlnYXRpb258ZW58MXx8fHwxNzczMjc3NzgzfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2023,
    rating: "16+",
    duration: "1h 52min",
    genre: ["Crime", "Thriller"],
  },
  {
    id: 17,
    title: "Mémoires d'Époque",
    description: "Un drame historique captivant qui retrace une période charnière de l'histoire.",
    image: "https://images.unsplash.com/photo-1769374072172-7a4f7c208f90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoaXN0b3JpY2FsJTIwcGVyaW9kJTIwZHJhbWF8ZW58MXx8fHwxNzczMjQ2ODczfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2024,
    rating: "13+",
    duration: "2h 25min",
    genre: ["Historique", "Drame"],
  },
  {
    id: 18,
    title: "Front de Guerre",
    description: "Une épopée de guerre qui montre le courage et le sacrifice des soldats.",
    image: "https://images.unsplash.com/photo-1770985274315-f728b6e2b844?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXIlMjBiYXR0bGVmaWVsZCUyMHNvbGRpZXJ8ZW58MXx8fHwxNzczMjQ4MTA0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2023,
    rating: "18+",
    duration: "2h 35min",
    genre: ["Guerre", "Drame"],
  },
  {
    id: 19,
    title: "La Mélodie du Succès",
    description: "L'histoire inspirante d'un musicien qui poursuit son rêve contre vents et marées.",
    image: "https://images.unsplash.com/photo-1767969457898-51d5e9cf81d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtdXNpYyUyMGNvbmNlcnQlMjBwZXJmb3JtYW5jZXxlbnwxfHx8fDE3NzMxNjU3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2024,
    rating: "10+",
    duration: "1h 48min",
    genre: ["Musical", "Drame"],
  },
  {
    id: 20,
    title: "Victoire Finale",
    description: "Un film sportif inspirant sur une équipe qui défie tous les pronostics.",
    image: "https://images.unsplash.com/photo-1763854413165-1713bc5a7f4a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcG9ydHMlMjBzdGFkaXVtJTIwYWN0aW9ufGVufDF8fHx8MTc3MzIxOTUyMXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    year: 2025,
    rating: "Tous publics",
    duration: "2h 08min",
    genre: ["Sport", "Drame"],
  },
];

export const categories = [
  { id: "trending", name: "Tendances actuelles", movieIds: [1, 2, 13, 15, 9] },
  { id: "action", name: "Action & Aventure", movieIds: [1, 8, 13, 11, 14] },
  { id: "scifi", name: "Science-Fiction", movieIds: [2, 15, 13] },
  { id: "drama", name: "Drames", movieIds: [3, 7, 11, 17, 18, 19, 20] },
  { id: "comedy", name: "Comédies", movieIds: [4] },
  { id: "thriller", name: "Thrillers", movieIds: [5, 8, 12, 16] },
  { id: "family", name: "Famille & Animation", movieIds: [6, 9, 10, 20] },
];
