/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmsCategorieRouteImport } from './routes/films.$categorie'
import { Route as FilmIdRouteImport } from './routes/film.$id'
import { Route as FilmImdbIdRouteImport } from './routes/film.$imdbId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsCategorieRoute = FilmsCategorieRouteImport.update({
  id: '/$categorie',
  path: '/$categorie',
  getParentRoute: () => FilmsRoute,
} as any)
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmImdbIdRoute = FilmImdbIdRouteImport.update({
  id: '/film/$imdbId',
  path: '/film/$imdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/film/$id': typeof FilmIdRoute
  '/film/$imdbId': typeof FilmImdbIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/film/$id': typeof FilmIdRoute
  '/film/$imdbId': typeof FilmImdbIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/film/$id': typeof FilmIdRoute
  '/film/$imdbId': typeof FilmImdbIdRoute
  '/films/$categorie': typeof FilmsCategorieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discussion'
    | '/films'
    | '/login'
    | '/profile'
    | '/register'
    | '/search'
    | '/auth/callback'
    | '/film/$id'
    | '/film/$imdbId'
    | '/films/$categorie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discussion'
    | '/films'
    | '/login'
    | '/profile'
    | '/register'
    | '/search'
    | '/auth/callback'
    | '/film/$id'
    | '/film/$imdbId'
    | '/films/$categorie'
  id:
    | '__root__'
    | '/'
    | '/discussion'
    | '/films'
    | '/login'
    | '/profile'
    | '/register'
    | '/search'
    | '/auth/callback'
    | '/film/$id'
    | '/film/$imdbId'
    | '/films/$categorie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscussionRoute: typeof DiscussionRoute
  FilmsRoute: typeof FilmsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FilmIdRoute: typeof FilmIdRoute
  FilmImdbIdRoute: typeof FilmImdbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$categorie': {
      id: '/films/$categorie'
      path: '/$categorie'
      fullPath: '/films/$categorie'
      preLoaderRoute: typeof FilmsCategorieRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/film/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$imdbId': {
      id: '/film/$imdbId'
      path: '/film/$imdbId'
      fullPath: '/film/$imdbId'
      preLoaderRoute: typeof FilmImdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FilmsRouteChildren {
  FilmsCategorieRoute: typeof FilmsCategorieRoute
}

const FilmsRouteChildren: FilmsRouteChildren = {
  FilmsCategorieRoute: FilmsCategorieRoute,
}

const FilmsRouteWithChildren = FilmsRoute._addFileChildren(FilmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscussionRoute: DiscussionRoute,
  FilmsRoute: FilmsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FilmIdRoute: FilmIdRoute,
  FilmImdbIdRoute: FilmImdbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
